# Generated by Django 4.2.1 on 2023-05-14 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbmodels', '0001_create_model_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'type')},
        ),
    ]
